include: package:lint/analysis_options.yaml

# Not happy with the default? Customize the rules depending on your needs.
# Here are some examples:
linter:
    rules:
        # Use parameter order as in json response
        always_put_required_named_parameters_first: false

        # Util classes are awesome!
        avoid_classes_with_only_static_members: false

        slash_for_doc_comments: true

        package_api_docs: true

        public_member_api_docs: true

        comment_references: true
