name: Release Drafter

on:
    push:
        branches:
            - master
    pull_request:
        types: [opened, reopened, synchronize]

jobs:
    run_tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-java@v1
              with:
                  java-version: "12.x"
            - uses: subosito/flutter-action@v1
              with:
                  flutter-version: "2.8.1"
            - run: flutter pub get
            - run: flutter test
    update_release_draft:
        runs-on: ubuntu-latest
        steps:
            - uses: release-drafter/release-drafter@v5
              env:
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}
